[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/work/gamisodes-baby-einstein/"
  to = "/work/"
  status = 301

[[redirects]]
  from = "/work/gamisodes/"
  to = "/work/"
  status = 301
