-- Real client testimonials collected from past projects.
-- Safe to re-run: clears existing testimonials first so this stays the source of truth.
-- Run against your database once (e.g. via phpMyAdmin in cPanel, or mysql < seed_testimonials.sql).

DELETE FROM testimonials;

INSERT INTO testimonials (headline, quote, client_name, client_role, sort_order, is_active) VALUES
('Professional and enthusiastic about getting my vision right.', 'Game Nock Team had to redesign and iterate a number of times while working me. They stayed professional and enthusiastic about getting my vision right. I''m grateful for their patience and understanding while working with me. Will definitely be hiring again!', 'Ron Jones', 'Park Survivor Game', 1, 1),
('On point, on time and a really great team to work with.', 'Hasham and the Game Nock Team have been going above and beyond for team Blast Wheels! What started out as a vision has nearly come full to life in less than 14 weeks! On point, on time and really great team to be working with. Work has been made clean and professional. Problems are solved quickly and effortlessly. Highly recommend.', 'Kyle Karasz', 'Blast Wheels', 2, 1),
('Communication was clear, delivery was on time.', 'Great experience working together. Communication was clear, delivery was on time, and the overall quality exceeded expectations. Highly recommended.', 'Rebel Bees', 'Country Strike', 3, 1),
('Reliable, met every deadline, and took full responsibility for the work.', 'Hasham and the Game Nock Team did an excellent job on this project. They were always reliable, met every deadline, and took full responsibility for the work. What really stood out was their ability to solve problems quickly and effectively, they can handle complex challenges and code solutions for virtually any project. They also worked very well as a team and kept everything organized. I would highly recommend them.', 'Shen Deli Bao Fa', 'VR Breathing Device Simulation', 4, 1),
('Reliable, met every deadline, and took full responsibility for the work.', 'Hasham and the Game Nock Team did an excellent job on this project. They were always reliable, met every deadline, and took full responsibility for the work. What really stood out was their ability to solve problems quickly and effectively, they can handle complex challenges and code solutions for virtually any project. They also worked very well as a team and kept everything organized. I would highly recommend them.', 'sdliy Bo', 'Practice Machine Simulation', 5, 1),
('Delivered exactly to our requirements, in less time than agreed.', 'Hasham and the Game Nock Team were a pleasure to work with. They delivered our game exactly to our requirements in less time than we even agreed upon. I can''t recommend them enough to anyone looking for game development.', 'Julia Espona', 'Puzzle Game Design & Development', 6, 1),
('Excellent communicators who resolve problems quickly.', 'The Game Nock Team are excellent communicators, address concerns effectively, and can resolve problems quickly. I highly recommend them.', 'Wayne John', 'Multiplayer Mobile iOS Game Development', 7, 1),
('Goes above and beyond in a timely manner.', 'Amazing Game Nock Team. Goes above and beyond in more than a timely manner.', 'Daisy Seq', 'Back to School Board Game', 8, 1),
('Quick and precise. Could not ask for better help.', 'Amazing, quick and precise Game Nock Team. Could not ask for better help.', 'KukiFun', 'Convert Cartoon Into Game', 9, 1),
('Concise and clear.', 'Amazing job, the Game Nock Team is concise and clear.', 'Atul R', 'Toddler Game', 10, 1),
('Timely, and I''ll be back for more work.', 'Great job. Timely and will 100% ask the Game Nock Team for work again.', 'C Patel', 'Education Game', 11, 1),
('Exceeded my expectations in both design and functionality.', 'I had an amazing experience working with the Game Nock Team. They delivered a high-quality 2D game with seamless blockchain integration, exceeding my expectations in both design and functionality. The gameplay is smooth, the graphics are polished, and the blockchain features are implemented flawlessly.', 'Trey Russell', 'Blockchain Play-to-Earn Game', 12, 1),
('Highly skilled, professional, and dedicated to the best results.', 'Communication was excellent throughout the project, with regular updates and a clear understanding of my requirements. The Game Nock Team was highly skilled, professional, and dedicated to delivering the best results. I highly recommend them to anyone looking for top-notch game development services!', 'Oliver Harburt', 'Astronaut Ace', 13, 1),
('Would definitely work with them again in the future.', 'Would definitely work with them again in the future. Thanks for the great work!', 'Kofi Duah', 'Web3 Blockchain Tycoon Game', 14, 1),
('Top notch, responsive, and willing to go above and beyond.', 'Hasham and the Game Nock Team are top notch. They''re responsive and willing to go above and beyond to deliver on your project. Their strong talent and entrepreneurial spirit make them a great solution. Highly recommend.', 'Davis Brimer', 'Interactive Game Project', 15, 1),
('Always in touch, always ready for any complexity.', 'Hasham and the Game Nock Team are very responsible and active! They are always in touch, always ask questions and are always ready to fulfill any complexity of the project. We have done a lot of cool projects with them and in different directions, and the Game Nock Team always quickly understood the essence of the task and quickly made edits after all our tests. If you are looking for a team who will cope with your task and leave a good impression, contact Hasham and the Game Nock Team! We had experience in developing 3D and 2D action games, logic games and utility applications.', 'Tim M', 'Real-Life Quest with Wallet Integration, AR & Geolocation', 16, 1),
('Very skilled and coordinated perfectly.', 'The Game Nock Team is very skilled and coordinated perfectly. They are the best developers if you are looking to make a game.', 'Rich Brown', 'Multiplayer Boxing Game', 17, 1),
('Done perfectly, on time and without any overlaps.', 'Hasham and the Game Nock Team have done a lot of cool jobs for me during this contract. They were done perfectly, on time and without any overlaps. I am very glad I had the opportunity to work with them as they have a great understanding of the mechanics of game applications, are not afraid of complex applications and are always trying to develop and grow in results! The applications that were made were both 3D gaming, 2D gaming, and word game utilities. If you haven''t worked with them yet, I advise you to give it a try.', 'Mina T', 'VR Ambulance Simulation', 18, 1),
('Great team, thank you!', 'Great Team, thank you!', 'Bucky Soliman', 'VR VisionPro Simulation', 19, 1),
('Smart, efficient, great communication and highly skilled.', 'Hasham and the Game Nock Team are amazing developers! And a great team! Smart, efficient, great communication and highly skilled. Couldn''t have asked for more.', 'Garth Williams', 'Multiple 2D Hyper-Casual Games', 20, 1),
('Great at handling heavy logic in simple applications.', 'Thanks to Hasham and the Game Nock Team for their ability to handle heavy logic in simple applications and their correct ability to ask what they want to know. Thanks to their analytical and communication skills, we put together a great application that many others could not put together in months!', 'Jamie R', 'Multiple 3D Hyper-Casual Games', 21, 1),
('Interesting solutions and clarifying questions from day one.', 'Thank you Hasham and the Game Nock Team for a great job! They coped with the task quickly, made timely edits and were very responsible to the deadline. It is interesting to work with Hasham and the Game Nock Team: they offer interesting solutions to processes, they immediately ask clarifying questions before the start of the project and help to adjust the basic logic of the application from the development side. I will be glad to work with them again!', 'Nicholas Hatton', 'Azuma Game', 22, 1),
('Met the deadline and stayed responsive throughout.', 'Hasham and the Game Nock Team did an excellent job! They met the deadline, corrected a lot of subtleties and helped to rearrange the project to fit the necessary changes. They always kept in touch, asked questions in a timely manner and were very polite.', 'Chenzeb Faiz', 'Zombie Fighting Game', 23, 1),
('Attentive to detail, quality held up despite the fast turnaround.', 'Hasham and the Game Nock Team are amazing developers! They handled the task very quickly, were attentive to the work and made my adjustments to the project with quality. And despite the quick completion of the work, its quality remained in excellent condition. The team was always in touch, attentive to details and asked questions. It was a pleasure to communicate and work with them. And I hope that we will have more joint projects!', 'Iqbal H', '2D Fighting Project', 24, 1),
('A standout play-to-earn experience, delivered flawlessly.', 'I''m thoroughly impressed with Hasham and the Game Nock Team''s work on our project. They seamlessly integrated blockchain tech and multiplayer features into our 3D game, delivering a standout play-to-earn experience. Their professionalism, skill, and proactive problem-solving were outstanding. I highly recommend Hasham and the Game Nock Team for anyone seeking top-quality game development with a blockchain edge.', 'Zmagoslava Kuhel', '3D Endless Runner', 25, 1),
('No repetition needed, and the end product left us extremely happy.', 'Well the best thing was no repetition needed. As per my past experiences most of the time there were a lot of repetitions and a lot of communication to achieve what I wanted. Attention to detail. Communication. End product extremely happy. Best of luck to the skilled Game Nock Team.', 'Abdelrahman Nasreldin', 'Strategy Game', 26, 1),
('Incredibly impressed with their work integrating the Phantom wallet.', 'I recently hired Muhammad online to integrate the Phantom wallet into my C# game, and I must say that I am incredibly impressed with their work. He was able to easily authenticate the user and fetch their NFTs from their wallet, seamlessly integrating it into my game. Throughout the project, the developer communicated effectively and professionally, keeping me updated on their progress and addressing any concerns I had. I highly recommend this developer to anyone looking for a skilled and reliable developer for their project. Thank you for your hard work and dedication to making my game a success!', 'Hamza T', 'Cat Doodle Game', 27, 1),
('Great team! Thank you.', 'Great team! Thank you.', 'Flores', '24/7', 28, 1),
('A fruitful collaboration, full of excitement and cool projects.', 'Thanks to the Game Nock team about his developer skills! It was a fruitful collaboration, full of excitement and cool projects. The team did a great job with tasks on various topics, always handled revisions well, and helped find logical solutions to any challenges in the project. Thank you for your work, speed, and responsible approach!', 'Tbilisi', 'Rocket Space', 29, 1),
('Did everything ahead of schedule and followed all instructions.', 'The Game Nock Team did an excellent job. They did everything ahead of schedule and followed all instructions. In the process of work they actively helped and offered solutions to any difficulties that arose. They were always in touch and very responsible in their approach to the task.', 'Guibin Lin', 'Porting 13 Projects to iOS and Android', 30, 1);
